UNRWAHealthProgramme/Controllers/DoctorController.cs
using IUNRWA_DTOs.LabTestDto;
using IUNRWA_DTOs.NewFolder;
using IUNRWA_DTOs.PreviewDto;
using IUNRWA_DTOs.PreviewIllnessDto;
using IUNRWA_DTOs.PreviewLabTestDto;
using IUNRWA_DTOs.PreviewMedicineDto;
using IUNRWA_DTOs.ReservationDto;
using IUNRWA_DTOs.Views;
using IUNRWA_Repository.Repository.UserRepository;
using IUNRWA_Service.IllnessService;
using IUNRWA_Service.LabTestService;
using IUNRWA_Service.MedicineService;
using IUNRWA_Service.PersonService;
using IUNRWA_Service.PreviewLabTestService;
using IUNRWA_Service.PreviewMedicineService;
using IUNRWA_Service.PreviewService;
using IUNRWA_Service.ReservationService;
using IUNRWA_Service.TheMeasurementService;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace UNRWAHealthProgramme.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IUserRepository userRepository;
        private readonly IReservationService reservationService;
        private readonly IMedicineService medicineService;
        private readonly ILabTestService labTestService;
        private readonly IPersonService personService;
        private readonly IPreviewMedicineService previewMedicineService;
        private readonly ITheMeasurementService measurementService;
        private readonly IPreviewService previewService;
        private readonly IIllnessService illnessService;
        private readonly IPreviewLabTestService previewLabTestService;


        public DoctorController(IUserRepository userRepository, IReservationService reservationService, IMedicineService medicineService, ILabTestService labTestService, IPersonService personService, IPreviewMedicineService previewMedicineService, ITheMeasurementService measurementService, IPreviewService previewService, IIllnessService illnessService, IPreviewLabTestService previewLabTestService)
        {
            this.userRepository = userRepository;
            this.reservationService = reservationService;
            this.medicineService = medicineService;
            this.labTestService = labTestService;
            this.personService = personService;
            this.previewMedicineService = previewMedicineService;
            this.measurementService = measurementService;
            this.previewService = previewService;
            this.illnessService = illnessService;
            this.previewLabTestService = previewLabTestService;
        }

        #region View
        public async Task<IActionResult> Index()
        {
            var user = await userRepository.GetCurrentDoctor();
            var doctorReservations = await reservationService.GetDoctorQueueReservations(user.Id);
            DoctorViewDto dto = new();
            dto.User = user;
            dto.DoctorReservations = doctorReservations;
            if (doctorReservations.Count == 0) dto.DoctorReservations.Add(new ReservationDto());
            return View(dto);
        }
        public async Task<IActionResult> Medicines()
        {
            DoctorViewDto dto = new();
            var medicines = await medicineService.GetAllMedicine();
            dto.Medicines = medicines;
            dto.MedicineTypes = await medicineService.GetAllMedicineType();
            dto.User = await userRepository.GetCurrentDoctor();
            return View(dto);
        }
        public async Task<IActionResult> LabTests()
        {
            DoctorViewDto dto = new();
            dto.LabTests = await labTestService.GetAllLabTest();
            dto.LabTestTypes = await labTestService.GetAllLabTestTypes();
            dto.User = await userRepository.GetCurrentDoctor();
            return View(dto);
        }
        public async Task<IActionResult> Queue()
        {
            DoctorViewDto dto = new();
            var user = await userRepository.GetCurrentUser();
            var doctorReservations = await reservationService.GetDoctorQueueReservations(user.Id);
            dto.DoctorReservations = doctorReservations;
            dto.User = await userRepository.GetCurrentDoctor();
            return View(dto);
        }
        public async Task<IActionResult> AllNextReservations()
        {
            DoctorViewDto dto = new();
            var user = await userRepository.GetCurrentUser();
            dto.DoctorReservations = await reservationService.GetAllNextDoctorReservations(0, user.Id);
            dto.User = await userRepository.GetCurrentDoctor();
            return View(dto);
        }
        public async Task<IActionResult> AllPreview()
        {
            DoctorViewDto dto = new();
            var user = await userRepository.GetCurrentUser();
            var doctorReservations = await reservationService.GetAllPreview(0, user.Id);
            dto.DoctorReservations = doctorReservations;
            dto.User = await userRepository.GetCurrentDoctor();
            return View(dto);
        }

        public async Task<IActionResult> PatientInfo(int personId , int reservationId, int previewId)
        {
            DoctorViewDto dto = new();
            dto.LabTestResults = await previewLabTestService.GetAllLabTestResults(personId,0);
            dto.PersonInfo = await personService.GetById(personId);
            var medicinePreview = await previewMedicineService.GetAllTakenPreviewMedicine(personId);
            dto.LastMedicine = medicinePreview.FirstOrDefault();
            dto.ReservationId = reservationId;
            dto.PreviewId = previewId;
            dto.AllPatientMeasurements = await measurementService.GetAllPersonMeasurements(personId, 0);
            if(previewId == 0)
            {
                var preview = await previewService.AddPreview(new PreviewFormDto { PatientId = personId, ReservationId = reservationId });
                dto.PreviewId = preview.Id;
            }
            dto.User = await userRepository.GetCurrentDoctor();
            return View(dto);
        }
        public async Task<IActionResult> PatientLabTests(int personId, int previewId)
        {
            DoctorViewDto dto = new();
            dto.AllPatientLabTests = await previewLabTestService.GetAllLabTestResults(personId,0);
            dto.PersonInfo = await personService.GetById(personId);
            dto.LabTestTypes = await labTestService.GetAllLabTestTypes();
            dto.PreviewId = previewId;
            dto.User = await userRepository.GetCurrentDoctor();
            return View(dto);
        }
        public async Task<IActionResult> PatientMedicines(int personId, int previewId)
        {
            DoctorViewDto dto = new();
            dto.PersonInfo = await personService.GetById(personId);
            dto.AllPatientMedicine = await previewMedicineService.GetAllPreviewMedicine(personId);
            dto.MedicineTypes = await medicineService.GetAllMedicineType();
            dto.PreviewId = previewId;
            dto.User = await userRepository.GetCurrentDoctor();
            return View(dto);
        }
        public async Task<IActionResult> PatientNCDMedicines(int personId , int previewId)
        {
            DoctorViewDto dto = new();
            dto.PersonInfo = await personService.GetById(personId);
            dto.AllPatientMedicine = await previewMedicineService.GetAllNCDPreviewMedicine(personId);
            dto.MedicineTypes = await medicineService.GetAllMedicineType();
            dto.PreviewId=previewId;
             dto.PersonNCdMedicines= await previewMedicineService.GetAllNCDPreviewMedicine(personId);
            dto.User = await userRepository.GetCurrentDoctor();
            return View(dto);
        }
        public async Task<IActionResult> PatientMesurements(int personId, int previewId)
        {
            DoctorViewDto dto = new();
            dto.PersonInfo = await personService.GetById(personId);
            dto.AllPatientMeasurements = await measurementService.GetAllPersonMeasurements(personId);
            dto.AllMeasurements = await measurementService.GetAllMeasurements();
            dto.PreviewId = previewId;
            dto.User = await userRepository.GetCurrentDoctor();
            return View(dto);
        }
        public async Task<IActionResult> CreatePreview(int personId, int previewId)
        {
            DoctorViewDto dto = new();
            dto.PersonInfo = await personService.GetById(personId);
            dto.PreviewId = previewId;
            var medicines = await medicineService.GetAllMedicine();
            dto.Medicines = medicines.Where(e=>e.Amount >0).ToList();
            dto.MedicineTypes = await medicineService.GetAllMedicineType();
            dto.IllnessTypes = await illnessService.GetAllIllnessType();
            dto.LabTestTypes = await labTestService.GetAllLabTestTypes();
            dto.AllMeasurements = await measurementService.GetAllMeasurements();
            dto.User = await userRepository.GetCurrentDoctor();
            return View(dto);
        }
       
        #endregion
        #region Action
        public async Task<IActionResult> RemoveReservation(int reservationId)
        {

            await reservationService.RemoveReservation(reservationId);
            return Redirect("~/Doctor/Queue");

        }
        public async Task<IActionResult> AddPreviewMedicin(int previewId, int previewMedicineId, int medicineAmount)
        {
            var dto = new PreviewMedicineFormDto { Amount = medicineAmount, PreviewId= previewId, MedicineId = previewMedicineId };
            await previewMedicineService.AddPreviewMedicine(dto);
            return Ok();
        }
        public async Task<IActionResult> AddPreviewIllness(int previewId, int previewIllnessId)
        {
            var dto = new PreviewIllnessFormDto {PreviewId = previewId, IllnessId = previewIllnessId };
            var result = await illnessService.AddPreviewIllness(dto);
            return Ok(result);
        }
        public async Task<IActionResult> AddLabTestToPreview(int previewId, int PreviewLabTestId, DateTime labTestDate)
        {

UNRWAHealthProgramme/Controllers/DoctorsController.cs
using IUNRWA_DTOs.DoctorDto;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;

namespace UNRWAHealthProgramme.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class DoctorsController : ControllerBase
    {
        private readonly IDoctorService service;

        public DoctorsController(IDoctorService service)
        {
            this.service = service;
        }
        [HttpGet]
        public async Task<IActionResult> GetAllDoctors()
        {
            var result = await service.GetAllDoctor();
            return Ok(result);
        }
    }
}

UNRWAHealthProgramme/Controllers/LabTestsController.cs
using IUNRWA_DTOs.LabTestDto;
using IUNRWA_DTOs.MedicineDto;
using IUNRWA_Model.Entity;
using IUNRWA_Service.LabTestService;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace UNRWAHealthProgramme.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class LabTestsController : ControllerBase
    {
        private readonly ILabTestService service;

        public LabTestsController(ILabTestService service)
        {
            this.service = service;
        }
        [HttpPost]
        [Route("[action]")]

        public async Task<IActionResult> AddLabTestType(string type)
        {
            await service.AddLabTestType(type);
            return Ok();
        }
        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> AddLabTest(LabTestFormDto formDto)
        {
            var result = await service.AddLabTest(formDto);
            return Ok(result);
        }
      
      
        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> GetAllLabTest(int? typeId = 0)
        {
            var result = await service.GetAllLabTest(typeId);
            return Ok(result);
        }

        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> GetAllNCDAnnualLabTest()
        {
            var result = await service.GetNCDAnnualOrMonthlyLabTest();
            return Ok(result);
        }
        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> GetAllLabeTestTypes()
        {
            var result = await service.GetAllLabTestTypes();
            return Ok(result);
        }
        [HttpDelete]
        [Route("[action]")]
        public async Task<IActionResult> RemoveAllLabTests()
        {
            await service.RemoveAllLabTests();
            return Ok();
        }
        [HttpDelete]
        [Route("[action]")]
        public async Task<IActionResult> RemoveAllLabTestTypes()
        {
            await service.RemoveAllLabTestTypes();
            return Ok();
        }
    }
    

}

UNRWAHealthProgramme/Controllers/MedicinesController.cs
using IUNRWA_DTOs.MedicineDto;
using IUNRWA_Service.MedicineService;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace UNRWAHealthProgramme.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class MedicinesController : ControllerBase
    {
        private readonly IMedicineService service;

        public MedicinesController(IMedicineService service)
        {
            this.service = service;
        }
        [HttpPost]
        [Route("[action]")]

        public async Task<IActionResult> AddMedicineType(string type)
        {
           await service.AddMedicineType(type);
            return Ok();
        }
        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> AddMedicines(MedicineFormDto formDto)
        {
            var result = await service.AddMedicine(formDto);
            return Ok(result);
        }
        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> GetMedicines(int? typeId =0)
        {
            var result = await service.GetAllMedicine(typeId);
            return Ok(result);
        }
        [HttpGet]
        [Route("[action]")]

        public async Task<IActionResult> GetMedicineType()
        {
            var result = await service.GetAllMedicineType();
            return Ok(result);
        }
    }
}

UNRWAHealthProgramme/Views/Doctor/AllNextReservations.cshtml
@model DoctorViewDto
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Next Reservations</title>
    <link rel="stylesheet" href="~/css/Queue.css">

    <!--Table Links-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" id="bootstrap-css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.csshttps://cdn.datatables.net/1.13.5/css/dataTables.bootstrap4.min.css">
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/dataTables.bootstrap4.min.js"></script>
</head>
<body>
    @section Scripts{
            <partial name="_ValidationScriptsPartial">
            }
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #1d86df; height: 3.5rem;">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon" style="font-size: 17px;"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNavDropdown" style="background-color: #1d86df;">
                <ul class="navbar-nav" style="background-color: #1d86df;">
                    <li class="nav-item active">
                        <a class="navbar-brand ">
                            <img src="~/images/user-color-64.png" alt="logo" class="img1 img-fluid">
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.UserName</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.HealthCenter.Name Center</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.Team.Name Team</a>

                    </li>
                    <li class="nav-item active">
                        <a asp-action="Index" asp-controller="Doctor" class="nav-link btn" id="logout-icon"
                           style="font-size: 17px; border: solid 1px; width: 132px; padding: 6px;text-align: center;">
                            Back
                        </a>

                    </li>
                    <li class="nav-item active">
                        <a asp-action="Logout" asp-controller="Clerick" class="nav-link btn" id="logout-icon"
                           style="font-size: 17px; border: solid 1px; width: 132px; padding: 6px;text-align: center;">
                            Logout
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z" />
                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                            </svg>
                        </a>

                    </li>


                </ul>
            </div>
            <div class="nav__icons">
                <img src="~/images/unrwa-logo-0DB0E000FE-seeklogo.com.png" alt="logo" class=" img__1 img-fluid">
            </div>


        </nav>


    <div class="container" style="color: #1d86df;  margin-top: 7rem;">
        <div class="row">
                <div class="form-group" style="color: #1d86df; width:230px; margin:auto; margin-bottom:20px">
                    <h4>@Model.DoctorReservations.Count() Next Reservations</h4>
            </div>
        </div>
            <table id="example" class="table table-striped table-bordered">
                <thead>
                    <tr>

                        <th> Person Id</th>
                        <th> Person Name</th>
                        <th style="width: 20%;">Date</th>
                        <th style="width: 30%;">Action</th>

                    </tr>
                </thead>
                <tbody>

                @foreach (var item in Model.DoctorReservations)
                {
                        <tr>

                            <td>@item.PersonId</td>
                            <td>@item.PersonName</td>
                            <td>@item.Date.ToShortDateString() @item.Date.ToShortTimeString()</td>
                            <td>
                                <a asp-action="PatientInfo" asp-controller="Doctor" asp-route-personId="@item.PersonId" asp-route-reservationId="@item.ReservationId" data-scroll class="btn btn-light btn-radius button_1 btn-brd grd1 effect-1">Patient Info </a>
                            </td>
                        </tr>
                }

                </tbody>
            </table>

    </div>
    <script src="~/js/QUEUE.js"></script>

</body>
</html>
<style>
    #example_wrapper {
        box-shadow: 0em 0em 20px 0px #9e9e9e;
        padding: 27px;
    }
</style>

UNRWAHealthProgramme/Views/Doctor/AllPreview.cshtml
@model DoctorViewDto
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Previews</title>
    <link rel="stylesheet" href="~/css/Queue.css">
    <link rel="stylesheet" href="~/css/All/Toaster.css">
    <!--Table Links-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" id="bootstrap-css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.csshttps://cdn.datatables.net/1.13.5/css/dataTables.bootstrap4.min.css">
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/dataTables.bootstrap4.min.js"></script>
    <!--Icon Link-->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    @section Scripts{
            <partial name="_ValidationScriptsPartial">
            }
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #1d86df; height: 3.5rem;">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon" style="font-size: 17px;"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNavDropdown" style="background-color: #1d86df;">
                <ul class="navbar-nav" style="background-color: #1d86df;">
                    <li class="nav-item active">
                        <a class="navbar-brand ">
                            <img src="~/images/user-color-64.png" alt="logo" class="img1 img-fluid">
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.UserName</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.HealthCenter.Name Center</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.Team.Name Team</a>

                    </li>
                    <li class="nav-item active">
                        <a asp-action="Index" asp-controller="Doctor" class="nav-link btn" id="logout-icon"
                           style="font-size: 17px; border: solid 1px; width: 132px; padding: 6px;text-align: center;">
                            Back
                        </a>

                    </li>
                    <li class="nav-item active">
                        <a asp-action="Logout" asp-controller="Clerick" class="nav-link btn" id="logout-icon"
                           style="font-size: 17px; border: solid 1px; width: 132px; padding: 6px;text-align: center;">
                            Logout
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z" />
                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                            </svg>
                        </a>

                    </li>


                </ul>
            </div>
            <div class="nav__icons">
                <img src="~/images/unrwa-logo-0DB0E000FE-seeklogo.com.png" alt="logo" class=" img__1 img-fluid">
            </div>


        </nav>

    <div class="container" style="color: #1d86df;  margin-top: 7rem;">
        <div class="row">
                <div class ="form-group" style="width: 200px; margin: auto; margin-bottom: 25px">
                    <h4 style="display:inline;">@Model.DoctorReservations.Count() Preview</h4>
            </div>
        </div>
            <table id="example" class="table table-striped table-bordered">
                <thead>
                    <tr>

                        <th> Person Id</th>
                        <th> Person Name</th>
                        <th style="width: 20%;">Date</th>

                    </tr>
                </thead>
                <tbody>

                @foreach (var item in Model.DoctorReservations)
                {
                        <tr>

                            <td>@item.PersonId</td>
                            <td>@item.PersonName</td>
                            <td>@item.Date.ToShortTimeString()</td>

                        </tr>
                }
                </tbody>
            </table>

          
    </div>
    <script src="~/js/QUEUE.js"></script>

</body>
</html>
<style>
    #example_wrapper {
        box-shadow: 0em 0em 20px 0px #9e9e9e;
        padding: 27px;
    }
</style>