UNRWAHealthProgramme/Controllers/ClerickController.cs
using IUNRWA_DTOs.DoctorDto;
using IUNRWA_DTOs.PersonDto;
using IUNRWA_DTOs.ReservationDto;
using IUNRWA_DTOs.TimeSloteDto;
using IUNRWA_DTOs.Views;
using IUNRWA_Repository.Repository.UserRepository;
using IUNRWA_Service.AreaPlaceService;
using IUNRWA_Service.AreaService;
using IUNRWA_Service.AuthenticationService;
using IUNRWA_Service.FamilyCardService;
using IUNRWA_Service.PersonService;
using IUNRWA_Service.RelationshipService;
using IUNRWA_Service.ReservationService;
using IUNRWA_Service.StudyLevelService;
using IUNRWA_Service.TeamService;
using IUNRWA_Service.TheServiceService;
using IUNRWA_Service.TimeSloteService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace UNRWAHealthProgramme.Controllers
{
    [Authorize]
    #region constructor
    public class ClerickController : Controller
    {
        private readonly IFamilyCardService familyCardService;
        private readonly IPersonService personService;
        private readonly IAreaService areaService;
        private readonly IRelationshipService relationshipService;
        private readonly ITheServiceService theServiceService;
        private readonly ITeamService teamService;
        private readonly IDoctorService doctorService;
        private readonly IStudyLevelService studyLevelService;
        private readonly IReservationService reservationService;
        private readonly ITimeSloteServices timeSloteService;
        private readonly IAuthenticationService authenticationService;
        private IUserRepository userRepo;
        public ClerickController(IFamilyCardService familyCardService, IPersonService personService, IStudyLevelService studyLevelService, IAreaService areaService, IRelationshipService relationshipService, ITheServiceService theServiceService, ITeamService teamService, IDoctorService doctorService, IReservationService reservationService, ITimeSloteServices timeSloteService, IAuthenticationService authenticationService, IUserRepository userRepo)
        {
            this.familyCardService = familyCardService;
            this.personService = personService;
            this.studyLevelService = studyLevelService;
            this.areaService = areaService;
            this.relationshipService = relationshipService;
            this.theServiceService = theServiceService;
            this.teamService = teamService;
            this.doctorService = doctorService;
            this.reservationService = reservationService;
            this.timeSloteService = timeSloteService;
            this.authenticationService = authenticationService;
            this.userRepo = userRepo;
        }
        #endregion
        #region Views
        public async Task<IActionResult> Home()
        {
            ClerickViewsDto dto = new ClerickViewsDto();
            dto.User = await userRepo.GetClerick();
            return View(dto);
        }
        public async Task<IActionResult> Naming(int personId)
        {

            var dto = new ClerickViewsDto();
            dto.studyLevels = await studyLevelService.GetAllStudyLevel();
            dto.Areas = await areaService.GetAllArea();
            dto.Relationships = await relationshipService.GetAllRelationships();
            dto.PersonToUpdateDto = await personService.GetById(personId);
            dto.User = await userRepo.GetClerick();
            return View(dto);
        }
        public async Task<IActionResult> Reservations(int personId)
        {
            var dto = new ClerickViewsDto();
            dto.PersonId = personId;
            dto.PersonInfo = await personService.GetById(personId);
            dto.Services = await theServiceService.GetAllServices();
            dto.Teams = await teamService.GetAllTeams();
            dto.AllPersonReservations = await reservationService.GetReservations(personId,0);
            dto.User = await userRepo.GetClerick();
            return View(dto);
        }
        #endregion

        #region search
        public async Task<IActionResult> SearchByFamilyCard(ClerickViewsDto dto)
        {
            var familyCard = await familyCardService.GetFamilyCard(0, dto.FamilyCard);
            dto.FamilyCardObject = familyCard;
            dto.User = await userRepo.GetClerick();

            return View(nameof(Home), dto);
        }
        [HttpPost]
        public async Task<IActionResult> SearchByPersonId(ClerickViewsDto dto)
        {
            var person = await personService.GetById(dto.PersonId);
            dto.FamilyCardObject.People.Add(person);
            dto.User = await userRepo.GetClerick();
            return View(nameof(Home), dto);
        }
        public async Task<IActionResult> SearchByChildCard(ClerickViewsDto dto)
        {
            var person = await personService.GetByChildCard(dto.ChildCardNumber);
            dto.FamilyCardObject.People.Add(person);
            dto.User = await userRepo.GetClerick();
            return View(nameof(Home), dto);
        }
        public async Task<IActionResult> SearchByNCD(ClerickViewsDto dto)
        {
            var person = await personService.GetByNCD(dto.NCDNumber);
            dto.FamilyCardObject.People.Add(person);
            dto.User = await userRepo.GetClerick();
            return View(nameof(Home), dto);
        }
        #endregion

        #region Action
        [HttpPost]
        public async Task<IActionResult> Naming(ClerickViewsDto dto )
        {
            dto.User = await userRepo.GetClerick();
            try
            {
                await personService.UpdatePerson(dto.PersonToUpdateFormDto);
                TempData["EditIndividualSuccess"] = "success";
            }
            catch
            {
                TempData["EditIndividualFaild"] = "failed";
            }
            return Redirect("~/Clerick/Naming?personId=" + dto.PersonToUpdateFormDto.Id);

        }
        [HttpPost]
        public async Task<IActionResult> AddNormalReservation(ClerickViewsDto dto)
        {
            dto.User = await userRepo.GetClerick();

            try
            {
                dto.ReservationFormDto.TimeSlotId = dto.AjaxAvailableTimeSloteId;
                dto.ReservationFormDto.DoctorId = dto.AjaxDoctorByTeamId;
                dto.ReservationFormDto.Date = dto.AjaxDate;
                await reservationService.AddNormalReservation(dto.ReservationFormDto);
                TempData["SuccessAddNormalReservation"] = "success";
            }
            catch
            {
                TempData["FaildAddNormalReservation"] = "failed";
            }
            return Redirect("~/Clerick/Reservations?personId=" + dto.ReservationFormDto.PersonId);
            
        }
        [HttpPost]
        public async Task<IActionResult> AddQuickReservation(ClerickViewsDto dto)
        {
            dto.User = await userRepo.GetClerick();

            try
            {
                dto.ReservationFormDto.DoctorId = dto.AjaxDoctorByTeamIdQuick;

                await reservationService.AddQuickReservation(dto.ReservationFormDto);
                TempData["SuccessAddQuickAppointmet"] = "success";
            }
            catch 
            {
                TempData["FaildAddQuickAppointmet"] = "failed";
            }
            return Redirect("~/Clerick/Reservations?personId=" + dto.ReservationFormDto.PersonId);

        }
        [HttpPost]
        public async Task<IActionResult> UpdateReservation(ClerickViewsDto dto)
        {
            dto.User = await userRepo.GetClerick();
            dto.ReservationFormDto.TimeSlotId = dto.AjaxAvailableTimeSloteIdEdit;
            dto.ReservationFormDto.DoctorId = dto.AjaxDoctorByTeamIdEdit;
            dto.ReservationFormDto.Date = dto.AjaxDateEdit;
            await reservationService.UpdateNormalReservation(dto.ReservationFormDto);
            return Redirect("~/Clerick/Reservations?personId=" + dto.PersonId);

        }
        [HttpPost]
        public async Task<IActionResult> RemoveReservation(ClerickViewsDto dto)
        {
            dto.User = await userRepo.GetClerick();
            try
            {
                await reservationService.RemoveReservation(dto.ReservationId);
                TempData["SuccessDeleteAppointmet"] = "success";
            }
            catch
            {
                TempData["FaildDeleteAppointmet"] = "failed";
            }
            return Redirect("~/Clerick/Reservations?personId=" + dto.PersonId);

        }
        public async Task<IActionResult> Logout()
        {

            await authenticationService.Logout();
           
            return Redirect("~/Home/Index");

        }
        #endregion

        #region Ajax
        [HttpGet]
        public async Task<IActionResult> GetDoctorsInTeam(int teamId)
        {
            var result = await doctorService.GetAllDoctor(teamId);
            return Ok(result);
        }
        [HttpPost]
        public async Task<IActionResult>  GetAvaliabelTimeSlote(AvailableTimeSloteFormDto formDto)
        {
            var result = await timeSloteService.GetAvilableTimeSlote(formDto);
            return Ok(result);
        }
        public async Task<IActionResult> RemoveReservation(int id)
        {
            await reservationService.RemoveReservation(id);
            return Ok();
        }

        #endregion
    }
}

UNRWAHealthProgramme/Controllers/PharmacistController.cs
using IUNRWA_DTOs.Views;
using IUNRWA_Repository.Repository.UserRepository;
using IUNRWA_Service.PersonService;
using IUNRWA_Service.PreviewMedicineService;
using Microsoft.AspNetCore.Mvc;

namespace UNRWAHealthProgramme.Controllers
{
    public class PharmacistController : Controller
    {
       private readonly IPreviewMedicineService previewMedicineService;
       private readonly IUserRepository userRepository;

        public PharmacistController(IPreviewMedicineService previewMedicineService, IUserRepository userRepository)
        {
            this.previewMedicineService = previewMedicineService;
            this.userRepository = userRepository;
        }
        #region Views
        public async Task<IActionResult> Index()
        {
            var user = await userRepository.GetCurrentPharmascist();
            var dto = new PharmacistViewDto();
            dto.User = user;
            return View(dto);
        }
        public async Task<IActionResult> PharmacyRecords()
        {
            var dto = new PharmacistViewDto();
            dto.AllTakenPreviewMedicines = await previewMedicineService.GetAllTakenPreviewMedicine();
            dto.User = await userRepository.GetCurrentPharmascist();
            return View(dto);
        }
        public async Task<IActionResult> RecipeRecords()
        {
            var dto = new PharmacistViewDto();
            dto.RecipePersonsInfo = await previewMedicineService.GetAllPersonNamesToTakePreviewMedicine();
            dto.UnTakenPreviewMedicines = await previewMedicineService.GetAllUnTakenPreviewMedicine();
            dto.User = await userRepository.GetCurrentPharmascist();
            return View(dto);
        }
        #endregion
        #region Action
        public async Task<IActionResult> TakePreviewMedicines(int personId)
        {
            try
            {
                await previewMedicineService.TakePreviewMedicine(personId);
                TempData["TakeMedicinesSuccess"] = "success";
            }
            catch
            {
                TempData["TakeMedicinesFaild"] = "failed";
            }
            return Redirect("~/Pharmacist/RecipeRecords");
        }
        public async Task<IActionResult> UnTakePreviewMedicine(int previewMedicinId)
        {
            try
            {
                await previewMedicineService.UnTakePreviewMedicine(previewMedicinId);
                TempData["UnTakeMedicinesSuccess"] = "success";
            }
            catch
            {
                TempData["UnTakeMedicinesFaild"] = "failed";
            }
            return Redirect("~/Pharmacist/PharmacyRecords");
        }

        #endregion
    }
}

UNRWAHealthProgramme/Views/pharmacist/Index.cshtml
@model PharmacistViewDto

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/pharmacist/home_pharmacist2.css">
    <link rel="stylesheet" href="~/css/All/Toaster.css">

    <title>Home</title>
    <!--Table Links-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" id="bootstrap-css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.csshttps://cdn.datatables.net/1.13.5/css/dataTables.bootstrap4.min.css">
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/dataTables.bootstrap4.min.js"></script>
    <!--Icon Link-->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    @section Scripts{
            <partial name="_ValidationScriptsPartial">
            }
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #1d86df; height: 3.5rem;">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon" style="font-size: 17px;"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNavDropdown" style="background-color: #1d86df;">
                <ul class="navbar-nav" style="background-color: #1d86df;">
                    <li class="nav-item active">
                        <a class="navbar-brand ">
                            <img src="~/images/user-color-64.png" alt="logo" class="img1 img-fluid">
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.UserName</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.HealthCenter.Name Center</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.Team.Name Team</a>

                    </li>
                    <li class="nav-item active">
                        <a asp-action="Logout" asp-controller="Clerick" class="nav-link btn" id="logout-icon"
                           style="font-size: 17px; border: solid 1px; width: 132px; padding: 6px;text-align: center;">
                            Logout
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z" />
                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                            </svg>
                        </a>

                    </li>


                </ul>
            </div>
            <div class="nav__icons">
                <img src="~/images/unrwa-logo-0DB0E000FE-seeklogo.com.png" alt="logo" class=" img__1 img-fluid">
            </div>


        </nav>

    <div class="container ">
        <h1 class="text_1">How are you @Model.User.UserName ? </h1>

        <div class="row">


            <div class="col-lg-6 col-md-3 col-ms-6 img-fluid">

                <img src="~/images/Pharmacist/images3.jpg" class="immg"
                     style="width: 550px ;" height="350px">

            </div>
            <div class="col-lg-3 col-md-3 col-ms-6">
                <div class="service-time one" style="background:#2895f1; ">
                    <h1 class="text_2">Recipe Records</h1>
                            <a asp-action="RecipeRecords" asp-controller="Pharmacist"
                               class="btn btn-light btn-radius button_2 btn-brd grd1 effect-1"><i class='bx bx-right-arrow-alt' style="color:#2895f1 ; font-size: 30px; text-align: center;"></i></a>
                        </div>

            </div>
            <div class="col-lg-3 col-md-3 col-ms-6">
                <div class="service-time one" style="background:#2895f1; margin-top: 50px; ">
                    <h1 class="text_2">Pharmacy Recordes</h1>
                            <a asp-action="PharmacyRecords" asp-controller="Pharmacist"
                     class="btn btn-light btn-radius button_2 btn-brd grd1 effect-1"><i class='bx bx-right-arrow-alt' style="color:#2895f1 ; font-size: 30px; text-align: center;"></i></a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

UNRWAHealthProgramme/Views/pharmacist/PharmacyRecords.cshtml
@model PharmacistViewDto
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pharmacy Recordes</title>
    <link rel="stylesheet" href="~/css/pharmacist/pharmacyRecords2.css" />
    <script src="~/js/pharmacist/recipeRecords.js"></script>
    <link rel="stylesheet" href="~/css/All/Toaster.css">
   
    <!--Table Links-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" id="bootstrap-css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.csshttps://cdn.datatables.net/1.13.5/css/dataTables.bootstrap4.min.css">
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/dataTables.bootstrap4.min.js"></script>
    <!--Icon Link-->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

</head>
<body style=" padding: 16px 50px 50px 50px">
    @section Scripts{
            <partial name="_ValidationScriptsPartial">
            }
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #1d86df; height: 3.5rem; z-index:0;">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon" style="font-size: 17px;"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNavDropdown" style="background-color: #1d86df;">
                <ul class="navbar-nav" style="background-color: #1d86df;">
                    <li class="nav-item active">
                        <a class="navbar-brand ">
                            <img src="~/images/user-color-64.png" alt="logo" class="img1 img-fluid">
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.UserName</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.HealthCenter.Name Center</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.Team.Name Team</a>

                    </li>
                    <li class="nav-item active">
                        <a asp-action="Index" asp-controller="Pharmacist" class="nav-link btn" id="logout-icon"
                           style="font-size: 17px; border: solid 1px; width: 132px; padding: 6px;text-align: center;">
                            Back
                        </a>

                    </li>
                    <li class="nav-item active">
                        <a asp-action="Logout" asp-controller="Clerick" class="nav-link btn" id="logout-icon"
                           style="font-size: 17px; border: solid 1px; width: 132px; padding: 6px;text-align: center;">
                            Logout
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z" />
                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                            </svg>
                        </a>

                    </li>


                </ul>
            </div>
            <div class="nav__icons">
                <img src="~/images/unrwa-logo-0DB0E000FE-seeklogo.com.png" alt="logo" class=" img__1 img-fluid">
            </div>


        </nav>

            <div id="snackbar">Some text some message..</div>
    @if (TempData["UnTakeMedicinesSuccess"] != null)
    {
                <script>
                    var x = document.getElementById("snackbar");
                    x.className = "show";
                    x.innerText = "Taken Medicins successfully"
                    setTimeout(function () { x.className = x.className.replace("show", ""); }, 3000);
                </script>
    }
    @if (TempData["UnTakeMedicinesFaild"] != null)
    {
                <script>
                    var x = document.getElementById("snackbar");
                    x.className = "error";
                    x.innerText = "Taken Medicins failed"
                    setTimeout(function () { x.className = x.className.replace("error", ""); }, 3000);
                </script>

    }
            <div class="text">
                <h1>Pharmacy recordes</h1>                
            </div>
        <table id="example" class="table table-striped table-bordered">
        <thead>
            <tr>

                    <th scope="col" style="color: #0071d1">Patient Name</th>
                    <th scope="col" style="color: #0071d1">Medicin Name</th>
                    <th scope="col" style="color: #0071d1">Amount</th>
                    <th scope="col" style="color: #0071d1">Action</th>
            </tr>
        </thead>
        <tbody>
            @{int i = 1;}
       @foreach (var item in Model.AllTakenPreviewMedicines)
            {
                if(i%2 != 0)
                    
                    {
                        <tr class="table-secondary">
                            <td scope="row" style="color: #0071d1">@item.PersonName</td>
                            <td scope="row" style="color: #0071d1">@item.Medicine.Name</td>
                            <td style="color: #0071d1">@item.Amount</td>
                                <td>
                                    <a asp-action="UnTakePreviewMedicine" asp-controller="Pharmacist" asp-route-previewMedicinId="@item.Id" type="button" class=" btn btn-outline-danger">UnTaken</a>
                                </td>
                        </tr>
                    }
                    else
                {
                            <tr>
                            <td style="color: #0071d1">@item.PersonName</td>
                            <td style="color: #0071d1">@item.Medicine.Name</td>
                            <td style="color: #0071d1">@item.Medicine.Amount</td>
                                <td>
                                    <a asp-action="UnTakePreviewMedicine" asp-controller="Pharmacist" asp-route-previewMedicinId="@item.Id" type="button" class="btn btn-outline-danger">UnTaken</a>

                                </td>
                            </tr>
                }
                i++;
            }
                  
        </tbody>
    </table>
</body>
</html>
<style>
    #example_wrapper {
        box-shadow: 0em 0em 20px 0px #9e9e9e;
        padding: 27px;
        padding-top: 0mm !important;
    }
</style>
<script src="~/js/QUEUE.js"></script>