UNRWAHealthProgramme/Controllers/NCDNurseController.cs
using IUNRWA_DTOs.NCDDto;
using IUNRWA_DTOs.Views;
using IUNRWA_Repository.Repository.UserRepository;
using IUNRWA_Service.FollowUpLabTestService;
using IUNRWA_Service.LabTestService;
using IUNRWA_Service.LateComplicationSevice;
using IUNRWA_Service.NCDService;
using IUNRWA_Service.ReservationService;
using IUNRWA_Service.TheMeasurementService;
using Microsoft.AspNetCore.Mvc;

namespace UNRWAHealthProgramme.Controllers
{
    public class NCDNurseController : Controller
    {
        private readonly IUserRepository userRepository;
        private readonly IReservationService reservationService;
        private readonly INCDService nCDService;
        private readonly IFollowUpLabTestService followUpServiceService;
        private readonly ILabTestService labTestService;
        private readonly ITheMeasurementService mesurementService;
        private readonly ILateComplicationService lateComplicationService;

        public NCDNurseController(IUserRepository userRepository, IReservationService reservationService, INCDService nCDService, IFollowUpLabTestService followUpServiceService, ILabTestService labTestService, ITheMeasurementService mesurementService, ILateComplicationService lateComplicationService)
        {
            this.userRepository = userRepository;
            this.reservationService = reservationService;
            this.nCDService = nCDService;
            this.followUpServiceService = followUpServiceService;
            this.labTestService = labTestService;
            this.mesurementService = mesurementService;
            this.lateComplicationService = lateComplicationService;
        }

        #region View
        public async Task<IActionResult> Index()
        {
            NCDNurseViewDto dto = new();
            dto.User = await userRepository.GetCurrentNCDNurse();
            return View(dto);
        }
        public async Task<IActionResult> Queue()
        {
            NCDNurseViewDto dto = new();
            var user = await userRepository.GetCurrentUser();
            dto.Reservations = await reservationService.GetDoctorQueueReservations(user.Id);
            dto.User = await userRepository.GetCurrentNCDNurse();
            return View(dto);
        }
        public async Task<IActionResult> CreateNCDCard(int personId)
        {
            NCDNurseViewDto dto = new NCDNurseViewDto();
            NCDFormDto formDto = new NCDFormDto
            {
                personId = personId
            };
            dto.CreatedNCDCardInfo = await nCDService.AddNCDCard(formDto);
            dto.User = await userRepository.GetCurrentNCDNurse();
            return View(dto);
        }
        public async Task<IActionResult> NCDPatientInfo(int personId, int reservationId)
        {
            NCDNurseViewDto dto = new NCDNurseViewDto();
            dto.PersonId = personId;
            dto.FollowUpVisitId = await followUpServiceService.AddFollowUpVisit(personId);
            if (reservationId != 0) await reservationService.MakeReservationDone(reservationId);
            dto.User = await userRepository.GetCurrentNCDNurse();
            return View(dto);
        }
        public async Task<IActionResult> AnnualFolowUpLabTest(int personId, int followUpVisitId)
        {
            NCDNurseViewDto dto = new NCDNurseViewDto();
            dto.PersonId = personId;
            dto.FollowUpVisitId = followUpVisitId;
            dto.PersonAnnualLabTest = await followUpServiceService.GetAllPersonAnnualDoneFollowUpLabTest(personId);
            dto.AllNCDAnnualLabTest = await labTestService.GetNCDAnnualOrMonthlyLabTest(); // I test it
            dto.User = await userRepository.GetCurrentNCDNurse();
            return View(dto);
        }
        public async Task<IActionResult> MonthlyFolowUpLabTest(int personId, int followUpVisitId)
        {
            NCDNurseViewDto dto = new NCDNurseViewDto();
            dto.PersonId = personId;
            dto.FollowUpVisitId = followUpVisitId;
            dto.PersonMonthlyLabTest = await followUpServiceService.GetAllPersonMonthlyDoneFollowUpLabTest(personId);
            dto.AllNCDAnnualLabTest = await labTestService.GetNCDAnnualOrMonthlyLabTest(); // I test it
            dto.User = await userRepository.GetCurrentNCDNurse();
            return View(dto);
        }
        public async Task<IActionResult> PersonMesurements(int personId, int followUpVisitId)
        {
            NCDNurseViewDto dto = new NCDNurseViewDto();
            dto.PersonId = personId;
            dto.PersonMesurements = await mesurementService.GetAllPersonMeasurements(personId);
            dto.FollowUpVisitId = followUpVisitId;
            dto.User = await userRepository.GetCurrentNCDNurse();
            return View(dto);
        }
        public async Task<IActionResult> PersonLateComplication(int personId, int followUpVisitId)
        {
            NCDNurseViewDto dto = new NCDNurseViewDto();
            dto.PersonId = personId;
            dto.FollowUpVisitId = followUpVisitId;
            dto.PersonLateComplications = await lateComplicationService.GetAllPersonLateComplication(personId);
            dto.AllLateComplications = await lateComplicationService.GetAllLateComplications();
            dto.User = await userRepository.GetCurrentNCDNurse();
            return View(dto);
        }

        #endregion
        #region Action
        public async Task<IActionResult> RequestAnnualLabTests(int followUpVisitId, int personId)
        {
            try
            {
                await followUpServiceService.RequestAnnualLabTests(followUpVisitId); 
                TempData["RequestAnnualLabTestsSuccess"] = "success";
            }
            catch
            {
                TempData["RequestAnnualLabTestsFaild"] = "failed";
            }
            return Redirect("~/NCDNurse/AnnualFolowUpLabTest?personId="+personId+ "&followUpVisitId="+followUpVisitId);

        }
        [HttpPost]
        public async Task<IActionResult> AddFollowUpLateComplication(NCDNurseViewDto dto)
        {
            try
            {
                await lateComplicationService.AddFollowUpLateComplication(dto.FollowUpVisitId, dto.LateComplicationId, dto.LateComplicationStatus);
                TempData["success"] = "success";
            }
            catch
            {
                TempData["failed"] = "failed";
            }
            return Redirect("~/NCDNurse/PersonLateComplication?personId=" + dto.PersonId + "&followUpVisitId=" + dto.FollowUpVisitId);

        }

        public async Task<IActionResult> RequestMonthlyLabTests(int followUpVisitId, int personId)
        {
            try
            {
                await followUpServiceService.RequestMonthlyLabTests(followUpVisitId);
                TempData["RequestAnnualLabTestsSuccess"] = "success";
            }
            catch
            {
                TempData["RequestAnnualLabTestsFaild"] = "failed";
            }
            return Redirect("~/NCDNurse/MonthlyFolowUpLabTest?personId=" + personId + "&followUpVisitId=" + followUpVisitId);

        }
        public async Task<IActionResult> RequesNCDMesurements(int followUpVisitId, int personId)
        {
            try
            {
                await mesurementService.RequestNCDMeasurement(personId,followUpVisitId); // I test it
                TempData["RequestMesurementSuccess"] = "success";
            }
            catch
            {
                TempData["RequestMesurementFaild"] = "failed";
            }
            return Redirect("~/NCDNurse/PersonMesurements?personId=" + personId + "&followUpVisitId=" + followUpVisitId);
        }
        #endregion
    }
}

UNRWAHealthProgramme/Controllers/TesterController.cs
using IUNRWA_DTOs.LabTestDto;
using IUNRWA_DTOs.Tester;
using IUNRWA_DTOs.Views;
using IUNRWA_Repository.Repository.UserRepository;
using IUNRWA_Service.FollowUpLabTestService;
using IUNRWA_Service.LabTestService;
using IUNRWA_Service.PersonService;
using IUNRWA_Service.PreviewLabTestService;
using IUNRWA_ShareKernal.Enum.LabTest;
using Microsoft.AspNetCore.Mvc;

namespace UNRWAHealthProgramme.Controllers
{
    public class TesterController : Controller
    {
        private readonly ILabTestService service;
        private readonly IPreviewLabTestService previewLabTestService;
        private readonly IFollowUpLabTestService followUpTestService;
        private readonly IPersonService personService;
        private readonly IUserRepository userRepository;

        public TesterController(ILabTestService service, IPreviewLabTestService previewLabTestService, IFollowUpLabTestService followUpTestService, IPersonService personService, IUserRepository userRepository)
        {
            this.service = service;
            this.previewLabTestService = previewLabTestService;
            this.followUpTestService = followUpTestService;
            this.personService = personService;
            this.userRepository = userRepository;
        }
        #region Views
        public async Task<IActionResult> Index()
        {
            TesterDto dto = new TesterDto();
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);
        }
        public async Task<IActionResult> LabTestManagement()
        {
            TesterDto dto = new TesterDto();
            dto.AllLabTest = await service.GetAllLabTest();
            dto.LabTestTypes = await service.GetAllLabTestTypes();
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);
        }
        public async Task<IActionResult> Queue()
        {
            var result = await previewLabTestService.GetAllUNDoneLabTest();
            TesterDto dto = new TesterDto();
            dto.Queue = result;
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);
        }
        public async Task<IActionResult> DoneTests()
        {
            var result = await previewLabTestService.GetAllDoneLabTest();
            TesterDto dto = new TesterDto();
            dto.User = await userRepository.GetCurrentTester();
            dto.DoneLabTest = result;
            return View(dto);
        }
        public async Task<IActionResult> DoneFollowUpTests()
        {
            var result = await followUpTestService.GetAllDoneFollowUpLabTest();
            TesterDto dto = new TesterDto();
            dto.DoneLabTest = result;
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);
        }
        public async Task<IActionResult> InsertTRResult( int sampleId)
        {
            var dto = new InsertLabTestResultDto
            {
                PreviewLabTestId = sampleId
            };
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);
        }
        public async Task<IActionResult> NCDInsertTRResult(int sampleId)
        {
            var dto = new InsertLabTestResultDto
            {
                PreviewLabTestId = sampleId
            };
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);
        }
        public async Task<IActionResult> InsertValueResult(int sampleId)
        {
            var dto = new InsertLabTestResultDto
            {
                PreviewLabTestId = sampleId
            };
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);
        }
        public async Task<IActionResult> NCDInsertValueResult(int sampleId)
        {
            var dto = new InsertLabTestResultDto
            {
                FollowUpLabTestId = sampleId
            };
            dto.User = await userRepository.GetCurrentTester();

            return View(dto);
        }
        public async Task<IActionResult> NCDQueue()
        {
            var result = await followUpTestService.GetAllUNDoneFollowUpLabTest();
            TesterDto dto = new TesterDto();
            dto.Queue = result;
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);
        }
        public async Task<IActionResult> NCDReports()
        {
           
            TesterDto dto = new TesterDto();
            dto.PersonNamesOfLabTestResults = await followUpTestService.GetPersonNamesOfFollowUpLabTestResults();
            foreach (var person in dto.PersonNamesOfLabTestResults)
            {
                person.LabTestsDates = await followUpTestService.GetDatesOfFollowUpLabTestResults(person.PersonId);

            }
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);
        }
        public async Task<IActionResult> Reports()
        {
            TesterDto dto = new TesterDto();
            dto.PersonNamesOfLabTestResults = await previewLabTestService.GetPersonNamesOfLabTestResults();
            foreach (var person in dto.PersonNamesOfLabTestResults)
            {
                person.LabTestsDates = await previewLabTestService.GetDatesOfLabTestResults(person.PersonId);

            }
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);
        }
        public async Task<IActionResult> NCDDoneTests()
        {

            var result = await followUpTestService.GetAllDoneFollowUpLabTest();
            TesterDto dto = new TesterDto();
            dto.DoneLabTest = result;
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);
        }
        public async Task<IActionResult> PersonLabTestsInDate(int personId, string date)
        {
           
            TesterDto dto = new TesterDto();
            dto.PersonLabTestResultInDate =await  previewLabTestService.GetAllLabTestResultsInDate(date,personId);
            dto.LabTestTypes =await service.GetAllLabTestTypes();
            dto.AllLabTest = await service.GetAllLabTest();
            dto.PersonInfo = await personService.GetById(personId);
            dto.DateOfLabTest = date;
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);

        }
        public async Task<IActionResult> NCDPersonLabTestsInDate(int personId, string date)
        {

            TesterDto dto = new TesterDto();
            dto.PersonLabTestResultInDate = await followUpTestService.GetAllFollowUpLabTestResultsInDate(date, personId);
            dto.LabTestTypes = await service.GetAllLabTestTypes();
            dto.AllLabTest = await service.GetAllLabTest();
            dto.PersonInfo = await personService.GetById(personId);
            dto.DateOfLabTest = date;
            dto.User = await userRepository.GetCurrentTester();
            return View(dto);

        }
        #endregion
        #region Action
        public async Task<IActionResult> MakeLabeTestAvailable(int labTestId)
        {
            try { 
                await service.MakeLabTestAvailable(labTestId);
                TempData["MakeAvailableSuccess"] = "success";
            }
            catch 
            {
                TempData["MakeAvailableFailed"] = "Failed";
            }
            return Redirect("~/Tester/LabTestManagement");

        }
        public async Task<IActionResult> MakeLabeTestUnAvailable(int labTestId)
        {
            try
            {
                await service.MakeLabTestUnAvailable(labTestId);
                TempData["MakeUnAvailableSuccess"] = "success";
            }
            catch
            {
                TempData["MakeUnAvailableFailed"] = "Failed";
            }
            return Redirect("~/Tester/LabTestManagement");

        }
        public async Task<IActionResult> RemoveLabTest(int labTestId)
        {
            try
            {
                await service.RemoveLabTest(labTestId);
                TempData["RemoveLabTestSuccess"] = "success";
            }
            catch
            {
                TempData["RemoveLabTestFailed"] = "Failed";
            }
            return Redirect("~/Tester/LabTestManagement");

        }
        public async Task<IActionResult> MakeLabTestDone(int previewLabTestId)
        {
            try
            {
                await previewLabTestService.MakePreviewLabTestDone(previewLabTestId);
                TempData["MakeLabTestDoneSuccess"] = "success";
            }
            catch
            {
                TempData["MakeLabTestDoneFailed"] = "Failed";
            }
            return Redirect("~/Tester/Queue");

        }
        public async Task<IActionResult> MakeFollowUpLabTestDone(int followUpLabTestId)
        {
            try
            {
                await followUpTestService.MakeFollowUpLabTestDone(followUpLabTestId);
                TempData["MakeLabTestDoneSuccess"] = "success";
            }
            catch
            {
                TempData["MakeLabTestDoneFailed"] = "Failed";
            }
            return Redirect("~/Tester/NCDQueue");

        }
        [HttpPost]
        public async Task<IActionResult> AddLabTest(TesterDto dto)
        {

            dto.LabTestToAdd = new LabTestFormDto
            {
                Name = dto.LabTestName,
                TypeId = dto.LabTestTypeId,
                NormalResultValue = dto.NormalLabTestSingleValue,
                MinNormalResult = dto.MinValue,
                MaxNormalResult = dto.MaxValue,
                Unit = dto.Unit,
                IsAvaliable = dto.IsAvilable,
                PNNormalResult = dto.TrueFalse
            };
            

            try
            {
                await service.AddLabTest(dto.LabTestToAdd);
                TempData["AddLabTestSuccess"] = "success";
            }
            catch(Exception ex) 

UNRWAHealthProgramme/Views/NCDNurse/AnnualFolowUpLabTest.cshtml
@model NCDNurseViewDto
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/NCDNurse/AnnualLabTest2.css" />
    <!--Table Links-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" id="bootstrap-css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.csshttps://cdn.datatables.net/1.13.5/css/dataTables.bootstrap4.min.css">
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/dataTables.bootstrap4.min.js"></script>
    <!--Icon Link-->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="~/css/All/Toaster.css" />
    <title>Document</title>
</head>
<body>
    <!--Notifications-->
    <div id="snackbar">Some text some message..</div>
    @if (TempData["RequestAnnualLabTestsSuccess"] != null)
    {
        <script>
            var x = document.getElementById("snackbar");
            x.className = "show";
            x.innerText = "Request Annual Lab Tests success"
            setTimeout(function () { x.className = x.className.replace("show", ""); }, 3000);
        </script>
    }
    @if (TempData["RequestAnnualLabTestsFaild"] != null)
    {
        <script>
            var x = document.getElementById("snackbar");
            x.className = "error";
            x.innerText = "Request Annual Lab Tests failed"
            setTimeout(function () { x.className = x.className.replace("error", ""); }, 3000);
        </script>

    }
    @section Scripts{
            <partial name="_ValidationScriptsPartial">
            }
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #1d86df; height: 3.5rem; z-index :0">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon" style="font-size: 17px;"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNavDropdown" style="background-color: #1d86df;">
                <ul class="navbar-nav" style="background-color: w;">
                    <li class="nav-item active">
                        <a class="navbar-brand ">
                            <img src="~/images/user-color-64.png" alt="logo" class="img1 img-fluid">
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.UserName</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.HealthCenter.Name Center</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.Team.Name Team</a>

                    </li>
                    <li class="nav-item active">
                        <a asp-action="NCDPatientInfo" asp-controller="NCDNurse" asp-route-personId="@Model.PersonId" asp-route-reservationId="0" class="nav-link btn" id="logout-icon"
                           style="font-size: 17px; border: solid 1px; width: 132px; padding: 6px;text-align: center;">
                            Back
                        </a>

                    </li>
                    <li class="nav-item active">
                        <a asp-action="Logout" asp-controller="Clerick" class="nav-link btn" id="logout-icon"
                           style="font-size: 17px; border: solid 1px; width: 132px; padding: 6px;text-align: center;">
                            Logout
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z" />
                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                            </svg>
                        </a>

                    </li>


                </ul>
            </div>
            <div class="nav__icons">
                <img src="~/images/unrwa-logo-0DB0E000FE-seeklogo.com.png" alt="logo" class=" img__1 img-fluid">
            </div>


        </nav>

    <div class="container">
        <h1 style="text-align: center; color: #1d86df; margin-top: 70px">
            Annual Lab Test result taken<br />
            During Follow_up visits
        </h1>

            <a asp-action="RequestAnnualLabTests" asp-controller="NCDNurse" asp-route-followUpVisitId="@Model.FollowUpVisitId" asp-route-personId="@Model.PersonId"
               style="color: aliceblue; width: auto; float: right !important;     margin-right: 65px; margin-bottom: 10px;"
           data-scroll
           class="btn btn-light btn-radius button_2 btn-brd grd1 effect-1">
           Request Annual
        </a>

        <div class="row" style="width: 100%">
                <table id="example"
                       class="table table-bordered"
                       style="width: 100% !important; margin-top: 50px">
                    <thead>
                        <tr>
                            <th style="width: 15%">Date</th>
                        @foreach (var item in Model.AllNCDAnnualLabTest)
                        {

                                <th>@item.Name (@item.Unit)</th>
                        }
                        </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model.PersonAnnualLabTest)
                    {
                            <tr>
                                <td>@item.Year</td>
                            @foreach (var result in item.LabTestResults)
                            {
                                    <td>
                                    @foreach (var labtest in Model.AllNCDAnnualLabTest)
                                    {
                                        @if (result.LabTestId == labtest.Id)
                                        {
                                            @result.Result

                                        }
                                    }
                                    </td>
                            }
                            </tr>
                    }
                    </tbody>
                </table>
            </div>
    </div>
</body>
</html>
<script src="~/js/QUEUE.js"></script>
<style>
    #example_wrapper {
        box-shadow: 0em 0em 20px 0px #9e9e9e;
        padding: 27px;
        padding-top: 10px;
        width: 90%;
        margin: auto;
    }
</style>

UNRWAHealthProgramme/Views/NCDNurse/Index.cshtml
@model NCDNurseViewDto
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/NCDNurse/Index.css" />
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet" />
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous" />
    <title>Document</title>
</head>
<body>
    @section Scripts{
            <partial name="_ValidationScriptsPartial">
            }
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #1d86df; height: 3.5rem; z-index :0">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon" style="font-size: 17px;"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNavDropdown" style="background-color: #1d86df;">
                <ul class="navbar-nav" style="background-color: w;">
                    <li class="nav-item active">
                        <a class="navbar-brand ">
                            <img src="~/images/user-color-64.png" alt="logo" class="img1 img-fluid">
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.UserName</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.HealthCenter.Name Center</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="font-size: 17px;">@Model.User.Team.Name Team</a>

                    </li>
                    <li class="nav-item active">
                        <a asp-action="Index" asp-controller="Tester" class="nav-link btn" id="logout-icon"
                           style="font-size: 17px; border: solid 1px; width: 132px; padding: 6px;text-align: center;">
                            Back
                        </a>

                    </li>
                    <li class="nav-item active">
                        <a asp-action="Logout" asp-controller="Clerick" class="nav-link btn" id="logout-icon"
                           style="font-size: 17px; border: solid 1px; width: 132px; padding: 6px;text-align: center;">
                            Logout
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z" />
                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                            </svg>
                        </a>

                    </li>


                </ul>
            </div>
            <div class="nav__icons">
                <img src="~/images/unrwa-logo-0DB0E000FE-seeklogo.com.png" alt="logo" class=" img__1 img-fluid">
            </div>


        </nav>

            <div class="container">
        <h1 class="text_1">Good morning Nurse</h1>

        <div class="row">
            <div class="col-lg-6 col-md-3 col-ms-6 img-fluid">
                <img src="~/images/000a5b8c0d773b5cbd5b8a5b3c9dd49c.webp"
                     class="immg"
                     style="width: 550px"
                     height="350px" />
            </div>
            <div class="col-lg-3 col-md-3 col-ms-6">
                <div class="service-time one" style="background: #2895f1">
                    <h1 class="text_2">Queue</h1>
                    <a asp-action="Queue" asp-controller="NCDNurse"
                        data-toggle="modal"
                            data-target="#exampleModal_3"
                            class="btn btn-light btn-radius button_2 btn-brd grd1 effect-1">
                        <i class="bx bx-right-arrow-alt"
                           style="color: #2895f1; font-size: 30px; text-align: center"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>